weather:
  api:
    key: d2929e9483efc82c82c32ee7e02d563e
    url: https://api.openweathermap.org/data/2.5/forecast
    fallback-path: classpath:mock-forecast.json
    cnt: 24
    offline-mode: false
