name: Build & Deploy Docker App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t grohit025/weather-backend ./Weather
          docker tag grohit025/weather-backend your-dockerhub-username/weather-backend:latest
          docker push grohit025/weather-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t grohit025/weather-frontend ./weather-ui
          docker tag grohit025/weather-frontend your-dockerhub-username/weather-frontend:latest
          docker push grohit025/weather-frontend:latest
